; Script for executing the tsc calculation
; Constants setup
c         = 2.998e10
AU        = 1.49598e13     ; Astronomical Unit       [cm]
pc        = 3.08572e18     ; Parsec                  [cm]
MS        = 1.98892e33     ; Solar mass              [g]
LS        = 3.8525e33      ; Solar luminosity        [erg/s]
RS        = 6.96e10        ; Solar radius            [cm]
G         = 6.67259e-8     ; Gravitational constant  [cm3/g/s^2]
yr        = 60*60*24*365.0 ; Years in seconds

; variable setup for tsc.pro
modeltime = 1e6   ; use a typical 1 million year age as a test
c_s = 0.35 * 1e5  ; 0.35 km/s from Terebey 1984
Omega_0 = 1e-14   ; Terebey 1984

; Grid Parameters
nx        = double(100.0)
ny        = double(400.0)
nz        = double(50.0)

; Model Parameters
;
; Manually input the model Parameters
rstar     = 5 * RS
R_env_max = 9.756000e+03 * AU
R_cen     = 1.500000e+01 * AU
rin       = rstar
rout      = R_env_max
rcen      = R_cen

; Make the Coordinates
;
ri           = rin * (rout/rin)^(dindgen(nx+1)/nx)
ri           = [0.0, ri]
thetai       = !pi*dindgen(ny+1)/ny
phii         = !pi*2.0*dindgen(nz+1)/nz

; Keep the constant cell size in r-direction
;
ri_cellsize = ri[1:-1]-ri[0:-2]
ind = (where(ri_cellsize/AU gt 100.0))[0]      ; The largest cell size is 100 AU
ri = [ri[0:ind], ri[ind]+dindgen(ceil((rout-ri[ind])/100/AU))*100*AU]
nx = n_elements(ri)-1    

; Assign the coordinates of the center of cell as its coordinates.
;
rc           = 0.5*( ri[0:nx-1]     + ri[1:nx] )
thetac       = 0.5*( thetai[0:ny-1] + thetai[1:ny] )
phic         = 0.5*( phii[0:nz-1]   + phii[1:nz] )

stop
indir = ''
outdir = ''
tsc, modeltime, c_s, Omega_0, rc, thetac, indir=indir, outdir=outdir
